require "user.colorschemetheme"
require "user.keymaps"
require "user.options"
require "user.plugins"
require "user.gui-clients"
require "user.autocommands"
--
require "lsp" -- ./lua/lsp/init.lua
--
require "plugin.impatient"
require "plugin.cmp"
require "plugin.telescope"
require "plugin.gitsigns"
require "plugin.treesitter"
require "plugin.autopairs"
require "plugin.comment"
require "plugin.lualine"
require "plugin.toggleterm"
require "plugin.project"
require "plugin.illuminate"
require "plugin.indentline"
require "plugin.dap"
require "plugin.leap"
require "plugin.whichkey"
require "plugin.cloak"
require "plugin.autotag"
require "plugin.multicursor"
require "plugin.aerial"
require "plugin.rnvimr"
require "plugin.noneckpain"
require "plugin.nvim-colorizer"
require "plugin.hotpot"

